/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'
import { Route as RentalsIdRouteImport } from './routes/rentals.$id'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as OrdersNumberRouteImport } from './routes/orders.$number'
import { Route as BookingsNumberRouteImport } from './routes/bookings.$number'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVehiclesRouteImport } from './routes/_authenticated/admin.vehicles'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRentalsRouteImport } from './routes/_authenticated/admin.rentals'
import { Route as AuthenticatedAdminPartsRouteImport } from './routes/_authenticated/admin.parts'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsIdRoute = RentalsIdRouteImport.update({
  id: '/rentals/$id',
  path: '/rentals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/parts/$id',
  path: '/parts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNumberRoute = OrdersNumberRouteImport.update({
  id: '/orders/$number',
  path: '/orders/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNumberRoute = BookingsNumberRouteImport.update({
  id: '/bookings/$number',
  path: '/bookings/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVehiclesRoute =
  AuthenticatedAdminVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRentalsRoute =
  AuthenticatedAdminRentalsRouteImport.update({
    id: '/rentals',
    path: '/rentals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartsRoute = AuthenticatedAdminPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bookings/$number': typeof BookingsNumberRoute
  '/orders/$number': typeof OrdersNumberRoute
  '/parts/$id': typeof PartsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bookings/$number': typeof BookingsNumberRoute
  '/orders/$number': typeof OrdersNumberRoute
  '/parts/$id': typeof PartsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bookings/$number': typeof BookingsNumberRoute
  '/orders/$number': typeof OrdersNumberRoute
  '/parts/$id': typeof PartsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/parts': typeof AuthenticatedAdminPartsRoute
  '/_authenticated/admin/rentals': typeof AuthenticatedAdminRentalsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vehicles': typeof AuthenticatedAdminVehiclesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/admin'
    | '/dashboard'
    | '/blog/$slug'
    | '/bookings/$number'
    | '/orders/$number'
    | '/parts/$id'
    | '/rentals/$id'
    | '/vehicles/$id'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/parts'
    | '/admin/rentals'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/dashboard'
    | '/blog/$slug'
    | '/bookings/$number'
    | '/orders/$number'
    | '/parts/$id'
    | '/rentals/$id'
    | '/vehicles/$id'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/orders'
    | '/admin/parts'
    | '/admin/rentals'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blog'
    | '/checkout'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/bookings/$number'
    | '/orders/$number'
    | '/parts/$id'
    | '/rentals/$id'
    | '/vehicles/$id'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/parts'
    | '/_authenticated/admin/rentals'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vehicles'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  BookingsNumberRoute: typeof BookingsNumberRoute
  OrdersNumberRoute: typeof OrdersNumberRoute
  PartsIdRoute: typeof PartsIdRoute
  RentalsIdRoute: typeof RentalsIdRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$id': {
      id: '/rentals/$id'
      path: '/rentals/$id'
      fullPath: '/rentals/$id'
      preLoaderRoute: typeof RentalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/parts/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$number': {
      id: '/orders/$number'
      path: '/orders/$number'
      fullPath: '/orders/$number'
      preLoaderRoute: typeof OrdersNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$number': {
      id: '/bookings/$number'
      path: '/bookings/$number'
      fullPath: '/bookings/$number'
      preLoaderRoute: typeof BookingsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vehicles': {
      id: '/_authenticated/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rentals': {
      id: '/_authenticated/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AuthenticatedAdminRentalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parts': {
      id: '/_authenticated/admin/parts'
      path: '/parts'
      fullPath: '/admin/parts'
      preLoaderRoute: typeof AuthenticatedAdminPartsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPartsRoute: typeof AuthenticatedAdminPartsRoute
  AuthenticatedAdminRentalsRoute: typeof AuthenticatedAdminRentalsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVehiclesRoute: typeof AuthenticatedAdminVehiclesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPartsRoute: AuthenticatedAdminPartsRoute,
  AuthenticatedAdminRentalsRoute: AuthenticatedAdminRentalsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVehiclesRoute: AuthenticatedAdminVehiclesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  BookingsNumberRoute: BookingsNumberRoute,
  OrdersNumberRoute: OrdersNumberRoute,
  PartsIdRoute: PartsIdRoute,
  RentalsIdRoute: RentalsIdRoute,
  VehiclesIdRoute: VehiclesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
